#!/usr/bin/fish
gsettings set org.gnome.shell disable-extension-version-validation true
gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com', 'launch-new-instance@gnome-shell-extensions.gcampax.github.com', 'alternate-tab@gnome-shell-extensions.gcampax.github.com', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'windowsNavigator@gnome-shell-extensions.gcampax.github.com', 'workspace-isolated-dash@n-yuki', 'taskwhisperer-extension@infinicode.de', 'netspeed-ng@giumo.x.clanjor-cjprods.org', 'iso-clock@giumo.x.clanjor-cjprods.org']"

